---
branches:
  - {{release_branch}}
tagFormat: v{{release_branch}}-${version}
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - #
    - "@semantic-release/github"
    - assets:
        - path: build/libs/*.jar
